
//Method for converting base64 to string
const data = {"response":"eyJzdWNjZXNzIjp0cnVlLCJjb2RlIjoiUEFZTUVOVF9TVUNDRVNTIiwibWVzc2FnZSI6IllvdXIgcGF5bWVudCBpcyBzdWNjZXNzZnVsLiIsImRhdGEiOnsibWVyY2hhbnRJZCI6IlBHVEVTVFBBWVVBVDE0MCIsIm1lcmNoYW50VHJhbnNhY3Rpb25JZCI6IjA0Yjc2NjU0LWQwMDktNDZlZi05N2UzLTVkNGQxYjk2N2UzZiIsInRyYW5zYWN0aW9uSWQiOiJUMjMxMjAzMjExOTU4OTcwMTk5NTYzNyIsImFtb3VudCI6ODk5MDAsInN0YXRlIjoiQ09NUExFVEVEIiwicmVzcG9uc2VDb2RlIjoiU1VDQ0VTUyIsInBheW1lbnRJbnN0cnVtZW50Ijp7InR5cGUiOiJORVRCQU5LSU5HIiwicGdUcmFuc2FjdGlvbklkIjoiMTk5NTQ2NDc3MyIsInBnU2VydmljZVRyYW5zYWN0aW9uSWQiOiJQRzIyMTIyOTE2MDcwODMzNDQ5MzQzMDAiLCJiYW5rVHJhbnNhY3Rpb25JZCI6bnVsbCwiYmFua0lkIjoiIn19fQ=="};

const string = Buffer.from(data.response,'base64').toString('ascii');

console.log(string);

